### ISSUE TITLE
can't open settlement : (

### ISSUE THREAD

**Issue by zrzz** [toconnell/kdm-manager#232]
We probably added non-ascii symbol into one of the input fields and ended up with no access to the campaign  : ( Can you please take a look? The campaign name is "Win-ter-fel" 
Traceback:
Traceback (most recent call last):
File "/home/toconnell/kdm-manager/v1/session.py", line 37, in wrapper
 return func(self, *args, **kwargs)
File "/home/toconnell/kdm-manager/v1/session.py", line 764, in current_view_html
 output += self.Settlement.render_html_summary(user_id=self.User.user["_id"])
File "/home/toconnell/kdm-manager/v1/assets.py", line 56, in wrapper
 view_html = Template(render_func(self, *args, **kwargs))
File "/home/toconnell/kdm-manager/v1/assets.py", line 5723, in render_html_summary
 endeavors = self.get_endeavors("html"),
File "/home/toconnell/kdm-manager/v1/assets.py", line 4294, in get_endeavors
 sources = copy(self.get_game_asset("innovations", update_mins=False, handles_to_names=True))
File "/home/toconnell/kdm-manager/v1/assets.py", line 5463, in get_game_asset
 name_list.append(lookup_dict[a_name]["name"])
KeyError: u'nigredo'

**Comment by toconnell** [comment]
@zrzz Hey--I can't look at this right now, but a lot of times, this can be caused by enabling expansion content, adding an item (e.g. resource) from that expansion and then removing the expansion content. 

When you get the traceback/failure, does it happen right when you sign into the Manager? Or does it happen when you try to view the settlement sheet or the campaign summary (i.e. when you click on the campaign from the dashboard)?

**Comment by toconnell** [comment]
@zrzz If you can sign in and view the dashboard, do me a favor and try to click on the settlement sheet: click on the "Settlements" button and then find your settlement and click on that link, instead of the link under "Campaigns". 

That should take you to the settlement sheet. If you can see the settlement sheet, use the controls on the side to see if you've got the Gorm expansion enabled. If you do not have it enabled, enabled it and see if you can view the campaign summary.

If none of that works, let me know, and I'll try to take a look at this in the next day.

**Comment by zrzz** [comment]
@toconnell wow, thank you very much, you were absolutely right and the way you have suggested fixed everything. indeed for some reason the gorm expansion got disabled. i also noticed that gorm was not displayed within the quarries list. thank you again for such a prompt and helpful reply, you are the best! : )

**Comment by toconnell** [comment]
@zrzz No problem! I'm sorry you ran into trouble with that issue: it's been known for a long time, but I have been moving and unable to work on the Manager, so it has gone un-fixed for too long!

At any rate, thanks again for using the Manager! Let me know if you run into any other issues.

Thanks again!
