### ISSUE TITLE
Campaign Summary: "Settlement Bonuses" are redundant/duplicative

### ISSUE THREAD

**Issue by WayForger** [toconnell/kdm-manager#264]
Though not an enormous issue, I think that there may be an error occurring in regards to which flavor text the convictions, "Survival of the Fittest" and "Graves," are displaying. This could possibly affect convictions not included in the screenshot. 
![screen shot 2017-07-25 at 6 44 56 pm](https://user-images.githubusercontent.com/30420007/28597050-d3b88552-7169-11e7-8ddb-21d460198ce4.png)

**Comment by toconnell** [comment]
@WayForger The apparent doubling here is due to the way that bonuses are categorized.

This isn't a bug, per se, but the way that the Campaign Summary view just dumps each and every settlement bonuses here is confusing and I agree that this needs some clean-up.

For the next release, I'll look at either a.) getting rid of some of the redundant ones, b.) condensing things into a single "all bonuses together" kind of thing or c.) some combination of the two.

**Comment by toconnell** [comment]
During the refactor of this, I think I'm going to re-do how Departing Survivors' Survival bonus works.

From email:

> Not really an issue, but more a feature request, it would be nice to have a counter where we can set our settlements Departing Survival as well, as there are different Innovations that add that stat and it is a pain to keep track of as well.

Me:
> That's a good idea: I think the approach would be to automate it, sort of like Survival Limit, so that the Manager always knows your minimum and then let users increase it above that, if they want to fiddle with it manually.
