### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by eugene-shuvaev** [toconnell/kdm-manager#375]
Hello Timothy,

I've tried to install kdm-manager on a fresh Ubuntu 16.04 LTS. Here is what happened (it was not the first run of install.sh):

```
Creating new init script...done.
Installing init script and starting server...
ln: failed to create symbolic link '/etc/init.d/kdm-manager': File exists
kdm-manager.service is not a native service, redirecting to systemd-sysv-install
Executing /lib/systemd/systemd-sysv-install enable kdm-manager
cat: /var/run/kdm-manager/server.pid: No such file or directory
CGI server 0.0.0.0:8012 has PID
Webapp init script installed; server started.
```
When I try to execute  `sudo /etc/init.d/kdm-manager start`, I get:
```
Traceback (most recent call last):
  File "./server.py", line 20, in <module>
    from utils import get_logger, load_settings, mdb
  File "/home/aidden/kdm-manager/v1/utils.py", line 24, in <module>
    import game_assets
ImportError: No module named game_assets
```

**Comment by toconnell** [comment]
Oh yeah: after the big upgrade to 1.5 (which removes that file), I never got around to updating the installer.

(The actual problem is pretty simple, if you want to try to hack around it: basically the legacy webapp's utils file wants to import the file _game_assets.py_, which is no longer part of the legacy webapp as of yesterday's release, and that import (and, really, anything to do with _game_assets.py_) has to be removed or changed, etc. 

Thanks for opening this issue. I'm going to stick some labels on it and put it into the backlog. There's still a bunch of 1.5 and The Watcher stuff that is going to take priority for now, but I'll get to it before the end of the year.

(If you feel like taking a run at it, please feel free: send me a PR and I'll take a look at your work, etc.)

Thanks again!

**Comment by eugene-shuvaev** [comment]
Ok, now it looks like:
```
sudo /etc/init.d//kdm-manager status

  PID MEMORY USER     GROUP    COMMAND         ARGS
16609 240152 aidden   aidden   python          python ./server.py

  File: '/var/run/kdm-manager/server.pid'
  Size: 6               Blocks: 8          IO Block: 4096   regular file
Device: 14h/20d Inode: 185269      Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/  aidden)   Gid: ( 1000/  aidden)
Access: 2017-10-29 22:02:57.433481612 +0000
Modify: 2017-10-29 21:54:47.752037143 +0000
Change: 2017-10-29 21:54:47.752037143 +0000
 Birth: -
```

```
tcp        0      0 *:8012                  *:*                     LISTEN
tcp        0      0 *:http                  *:*                     LISTEN
```

And still 502 from nginx.

**Comment by toconnell** [comment]
The is no longer relevant: installation of the V3 legacy webapp does not use any of this.
