### ISSUE TITLE
Language doesn't increase survival limit

### ISSUE THREAD

**Issue by CalebKester** [toconnell/kdm-manager#417]
It seems as if Language doesn't increase the survival limit. I know there's some talk about what survival limit the settlement starts at after language. I'm pretty sure once you get language you should have 2: https://boardgamegeek.com/article/21528269#21528269

Is this a bug in the api?

**Comment by toconnell** [comment]
I just checked: adding the innovation increases SL by one (so you have two, if you start a new settlement and add it).

Talk me through the workflow that's happening that makes it seem like it doesn't happen?

**Comment by Chaorain** [comment]
I added the Symposium Innovation to my settlements and the survival limit did not increase. I tried on both of my Settlements just to be sure.

**Comment by toconnell** [comment]
Alright, let's walk this through:

1. first we POST to _/settlement/add_innovation/oid_
1. next, we init/normalize/baseline the settlement object
1. then we hit the _add_innovation()_ method, which...
1. makes sure the incoming handle a.) is real and b.) isn't a dupe and then appends it to our list
1. we save
1. we do post-processing on the innovation's `current_survivor` rules

@CalebKester Are you looking at the JSON you get back from your request for a survival increase? Because I don't think, under current API workflow, that you would see the increase until the next _/settlement/get/oid_ (or similar call: basically any call that inits and normalizes the settlement).

**Comment by toconnell** [comment]
oh snap! we're always off by one because the minimum survival for a settlement is zero (and should be one).

This will fix the legacy webapp:

```
diff --git a/v2/api/models/settlements.py b/v2/api/models/settlements.py
index 52536a3..f8207e1 100644
--- a/v2/api/models/settlements.py
+++ b/v2/api/models/settlements.py
@@ -2600,7 +2600,7 @@ class Settlement(Models.UserAsset):
             return True
         elif return_type == 'min':

-            minimum = 0
+            minimum = 1

             # process innovations
             for i_dict in self.list_assets("innovations"):
```

@Chaorain Thanks for reporting! The patch for this will go out in the next release!

**Comment by CalebKester** [comment]
oh awesome. sorry for not getting that video sooner, glad you got to figuring it out first :)

**Comment by toconnell** [comment]
@CalebKester Well, here's a problem we might have for The Watcher. If you/@chibird12 are refreshing the on-screen settlement with the JSON you get back from your _/settlement/add_innovation/oid_ call, it won't be updated, I don't think.

Try this again after I push the next release and see how it looks in The Watcher. If it doesn't work, I think I can just call the API's _enforce_minimums()_ on the asset before I serialize it, but I want to avoid that (since it would be an exception to normal workflow, etc.).

Any way, I'm leaving the ticket open and tagging it in for the alpha until you give me the All Clear.

**Comment by CalebKester** [comment]
I experienced this in your app so this should hopefully fix it. I'll let you know if I still see an issue.

**Comment by toconnell** [comment]
Ahh @CalebKester OK, in that case, I'm going to close this out, then, since it fixes the bug there.
