### ISSUE TITLE
Some Errors and Suggestions :)

### ISSUE THREAD

**Issue by Manuel18071991** [toconnell/kdm-manager#540]
Hello, 
first of all i want to thank you so much for putting in work for this kdm manager. My friend and i use it alle the time when playing and it helps a lot with the tracking :) I subscribed a long time ago.
I want to report some issues we face very often when using it:

-) When updating the settlement storage it happens very often that it does make mistakes when saving (for example not adding some of the ressources i put in or not removing some i put out. It happens nearly every time i update the storrage wich results in double or tripple checking it)

-) We have the Empire Innovation and now every time i create a new survivor it gives out an error saying it didnt find prisitne ability

-) Saga doesnt add the bonuses forr newborn

-) It doesnt add arena as a nightmare consequence in the innvoation deck in the pots campagne

-) After manualy raising the survival limit due the Manhunter event which increases it by 2, the manager doesnt automaticly raise the limit anymore when innovating a new innovation with survival limit increase

Now some suggestions for better usage: the campain summary is very nice and fast to use but it happens that i dont use it very often because i dont see the stats of the survivors in that campaign summary, also notes are not there (which are very important in an pots campain). I dont want to klick every of my 20 survivor when i want to know which one has 1 luck or the most evasion so i use the search function on top to see the stats, but there on the other hand i dont see the weapon proficency. 
So my wish would be one overview which shows everything important (espacialy the stats + the weapon proficiency, which are the most important factors when deciding which survivor we depart). I like the campaign summary very much because it is so fast to use. It would be super nice to have that reaction speed everytime we click on edit a survivor or edit storage. Is there a way to improve the working speed of the whole site? 

Again thank you very much for all your work and keep on doing it :)

Greetings Manuel

**Comment by toconnell** [comment]
Hey @Manuel18071991 !

Thanks for taking the time to write all of this down!

You've got a few things here, so I've separated them out into individual tickets so that I can track them more easily:

- https://github.com/toconnell/kdm-manager/issues/541
- https://github.com/theLaborInVain/kdm-manager-api/issues/15
- https://github.com/theLaborInVain/kdm-manager-api/issues/16
- https://github.com/theLaborInVain/kdm-manager-api/issues/17
- https://github.com/toconnell/kdm-manager/issues/542

For the enhancement ideas, let me write some quick responses:

> Now some suggestions for better usage: the campain summary is very nice and fast to use but it happens that i dont use it very often because i dont see the stats of the survivors in that campaign summary, also notes are not there (which are very important in an pots campain).

Good news! At some point in the next couple of months, the Campaign Summary will be expanded and improved to include bigger and better Survivor "cards", which will include more survivor information in the main view, so that you don't have to click into various survivors.

Also, settlement notes are going to be totally redone, since they are not very useful at present. You can read more about plans for that here: https://github.com/toconnell/kdm-manager/issues/543

> I like the campaign summary very much because it is so fast to use. It would be super nice to have that reaction speed everytime we click on edit a survivor or edit storage. Is there a way to improve the working speed of the whole site?

This is a more difficult thing to accomplish, but I am working on it. For example, in the next release of the Manager, the Settlement Sheet will have tabs, and one of the tabs will be used for storage.

Here is a preview of how that is going to work:

![2020-01-03_settlement_sheet_tab_demo](https://user-images.githubusercontent.com/48043/71751403-0c293300-2e41-11ea-8d27-4364995af7cc.gif)

In a nutshell, the bit ideas are that:

1. the user opens the settlement sheet, which immediately loads just the basics of the settlement.
1. when the user clicks the 'Storage' tab, the storage loads, and then stays loaded alongside the settlement sheet.
1. if desired, the user can choose to refresh the keyword tallies or totals at the top of each storage group, but this does not affect the on-page storage display.

Changes are saved when they are made, but the whole storage never has to be refreshed or reloaded the way it does in the current version of the Manager.

Anyway, sorry for writing such a long response! I wanted to keep this short.

And thanks for taking the time to write in with the issues above: I really appreciate it! I expect to have most of them fixed in the next release of the Manager, which should be out before the end of January 2020.

Thanks again!

**Comment by toconnell** [comment]
Closing this, since it was only open for discussion purposes and all of the constituent issues have been spun off into their own tickets.
