### ISSUE TITLE
Suggestion for "create newborn" 

### ISSUE THREAD

**Issue by quebecsti** [toconnell/kdm-manager#548]
When using the "create newborn",  at the stage where we select mother and father, could you filter out the survivors that can't  have babies? ( ie  : destroyed genitals )

**Comment by toconnell** [comment]
Hey @quebecsti thanks for opening this issue!

This is probably actually a bug, because survivors who cannot participate in the Intimacy event should _not_ be included in the drop-down lists.

When you get a chance, can you email me the email address you are using and the name of the settlement where you are seeing the issue? 

toconnell@thelaborinvain.com is my email; if you prefer Twitter, send me a DM @kdmManager

Thanks!

**Comment by toconnell** [comment]
Hey @quebecsti!

I haven't been able to re-create this one, and I wonder if you've hit it again? If you have run into it and you get a chance, can you please let me know?

(Screen captures help.)

Thanks again!

**Comment by toconnell** [comment]
Hello @quebecsti!

I am going to leave this one open for another week or so while I collect the changes for the next release of the Manager, but if I don't see anything, I am going to close this one out.

If you get a chance to get into the manager and you see it again, please let me know!

Thanks!
TOC
